;;; emacs.el --- the vgs theme for Emacs  -*- lexical-binding: t -*-
;; Rendered by vgsh theme apply and loaded by vgs-theme.el in the custom
;; theme directory, so (load-theme 'vgs t) enables it and loading the theme
;; again reads this file again.
(deftheme vgs "The vgs desktop theme.")
(custom-theme-set-faces
 'vgs
 '(default ((t (:foreground "#@{color.text}" :background "#@{color.background}"))))
 '(cursor ((t (:background "#@{color.accent}"))))
 '(region ((t (:background "#@{color.borderStrong}" :extend t))))
 '(highlight ((t (:background "#@{color.surfaceHover}"))))
 '(hl-line ((t (:background "#@{color.surfaceRaised}" :extend t))))
 '(fringe ((t (:background "#@{color.background}"))))
 '(vertical-border ((t (:foreground "#@{color.border}"))))
 '(line-number ((t (:foreground "#@{color.textFaint}" :background "#@{color.background}"))))
 '(line-number-current-line ((t (:foreground "#@{color.text}" :background "#@{color.surfaceRaised}"))))
 '(mode-line ((t (:foreground "#@{color.text}" :background "#@{color.surfaceRaised}" :box nil))))
 '(mode-line-inactive ((t (:foreground "#@{color.textMuted}" :background "#@{color.surface}" :box nil))))
 '(minibuffer-prompt ((t (:foreground "#@{color.accent}"))))
 '(link ((t (:foreground "#@{color.info}" :underline t))))
 '(isearch ((t (:foreground "#@{color.onAccent}" :background "#@{color.accent}"))))
 '(lazy-highlight ((t (:background "#@{color.borderStrong}"))))
 '(show-paren-match ((t (:foreground "#@{color.accent}" :weight bold))))
 '(shadow ((t (:foreground "#@{color.textFaint}"))))
 '(error ((t (:foreground "#@{color.danger}"))))
 '(warning ((t (:foreground "#@{color.warning}"))))
 '(success ((t (:foreground "#@{color.success}"))))
 '(font-lock-comment-face ((t (:foreground "#@{color.textFaint}" :slant italic))))
 '(font-lock-doc-face ((t (:foreground "#@{color.textMuted}" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#@{terminal.color2}"))))
 '(font-lock-keyword-face ((t (:foreground "#@{terminal.color5}"))))
 '(font-lock-builtin-face ((t (:foreground "#@{terminal.color6}"))))
 '(font-lock-function-name-face ((t (:foreground "#@{terminal.color4}"))))
 '(font-lock-variable-name-face ((t (:foreground "#@{color.text}"))))
 '(font-lock-type-face ((t (:foreground "#@{terminal.color3}"))))
 '(font-lock-constant-face ((t (:foreground "#@{terminal.color6}"))))
 '(font-lock-preprocessor-face ((t (:foreground "#@{terminal.color1}"))))
 '(font-lock-warning-face ((t (:foreground "#@{color.warning}"))))
 '(ansi-color-black ((t (:foreground "#@{terminal.color0}" :background "#@{terminal.color0}"))))
 '(ansi-color-red ((t (:foreground "#@{terminal.color1}" :background "#@{terminal.color1}"))))
 '(ansi-color-green ((t (:foreground "#@{terminal.color2}" :background "#@{terminal.color2}"))))
 '(ansi-color-yellow ((t (:foreground "#@{terminal.color3}" :background "#@{terminal.color3}"))))
 '(ansi-color-blue ((t (:foreground "#@{terminal.color4}" :background "#@{terminal.color4}"))))
 '(ansi-color-magenta ((t (:foreground "#@{terminal.color5}" :background "#@{terminal.color5}"))))
 '(ansi-color-cyan ((t (:foreground "#@{terminal.color6}" :background "#@{terminal.color6}"))))
 '(ansi-color-white ((t (:foreground "#@{terminal.color7}" :background "#@{terminal.color7}"))))
 '(ansi-color-bright-black ((t (:foreground "#@{terminal.color8}" :background "#@{terminal.color8}"))))
 '(ansi-color-bright-red ((t (:foreground "#@{terminal.color9}" :background "#@{terminal.color9}"))))
 '(ansi-color-bright-green ((t (:foreground "#@{terminal.color10}" :background "#@{terminal.color10}"))))
 '(ansi-color-bright-yellow ((t (:foreground "#@{terminal.color11}" :background "#@{terminal.color11}"))))
 '(ansi-color-bright-blue ((t (:foreground "#@{terminal.color12}" :background "#@{terminal.color12}"))))
 '(ansi-color-bright-magenta ((t (:foreground "#@{terminal.color13}" :background "#@{terminal.color13}"))))
 '(ansi-color-bright-cyan ((t (:foreground "#@{terminal.color14}" :background "#@{terminal.color14}"))))
 '(ansi-color-bright-white ((t (:foreground "#@{terminal.color15}" :background "#@{terminal.color15}")))))
(provide-theme 'vgs)
