# The vgs theme for kitty, included from kitty.conf by vgsh theme apply.
foreground #@{palette.foreground}
background #@{palette.background}
selection_foreground #@{palette.foreground}
selection_background #@{color.borderStrong}
cursor #@{palette.foreground}
cursor_text_color #@{palette.background}
url_color #@{palette.accent}
color0 #@{terminal.color0}
color1 #@{terminal.color1}
color2 #@{terminal.color2}
color3 #@{terminal.color3}
color4 #@{terminal.color4}
color5 #@{terminal.color5}
color6 #@{terminal.color6}
color7 #@{terminal.color7}
color8 #@{terminal.color8}
color9 #@{terminal.color9}
color10 #@{terminal.color10}
color11 #@{terminal.color11}
color12 #@{terminal.color12}
color13 #@{terminal.color13}
color14 #@{terminal.color14}
color15 #@{terminal.color15}
